# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# PPO configuration for Create 3 navigation with custom feature extractor
seed: 42

n_timesteps: !!float 1e7
policy: 'MultiInputPolicy'
n_steps: 32
batch_size: 4096
gae_lambda: 0.95
gamma: 0.99
n_epochs: 10
ent_coef: 0.005
learning_rate: !!float 3e-4
clip_range: !!float 0.2
policy_kwargs:
  features_extractor_class: "rl_navigation.feature_extractor.NavigationFeaturesExtractor"
  features_extractor_kwargs:
    features_dim: 134
  net_arch:
    pi: [128, 64]
    vf: [128, 64]
  activation_fn: nn.ELU
  squash_output: False
vf_coef: 0.5
max_grad_norm: 0.5
normalize_input: True
clip_obs: 10.0
device: "cuda:0"
